import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    img: "https://res.cloudinary.com/dgiibcwd7/image/upload/v1689067458/ecommerce-images/59795331_ngmem9.jpg",
    name: "Do Epic Shit",
    author: "Ankur Warikoo",
    price: 219,
    originalPrice: 399,
    isBestSeller: true,
    category: "Horror",
    rating: 4.6,
  },
  {
    _id: uuid(),
    img: "https://res.cloudinary.com/dgiibcwd7/image/upload/v1689068871/ecommerce-images/Believe-in-Yourself_te5ank.png",
    name: "Believe In Yourself",
    author: "Joseph",
    price: 250,
    originalPrice: 1200,
    isBestSeller: false,
    category: "Horror",
    rating: 4,
  },

  {
    _id: uuid(),
    img: "https://res.cloudinary.com/dgiibcwd7/image/upload/v1689068917/ecommerce-images/51JkDEpHUQL_odmczn.jpg",
    name: "Zero To One",
    author: "Peter Thiel",
    price: 50,
    originalPrice: 500,
    isBestSeller: false,
    category: "Fiction",
    rating: 2,
  },
  {
    _id: uuid(),
    img: "https://res.cloudinary.com/dgiibcwd7/image/upload/v1689068955/ecommerce-images/81bGKUa1e0L._AC_UF1000_1000_QL80__fxrrjp.jpg",
    name: "Atomic Habits",
    author: "James Clear",
    price: 390,
    originalPrice: 790,
    isBestSeller: true,
    category: "Horror",
    rating: 4.8,
  },

  {
    _id: uuid(),
    img: "https://res.cloudinary.com/dgiibcwd7/image/upload/v1689068988/ecommerce-images/41SG4SO4T9L_lbu462.jpg",
    name: "IKIGAI",
    author: "Hector Garcia",
    price: 600,
    originalPrice: 1500,
    isBestSeller: false,
    category: "Non Fiction",
    rating: 4,
  },
  {
    _id: uuid(),
    img: "https://res.cloudinary.com/dgiibcwd7/image/upload/v1689069019/ecommerce-images/81bsw6fnUiL._AC_UF1000_1000_QL80__sjffmg.jpg",
    name: "Rich Dad Poor Dad",
    author: "Robert Kiyoski",
    price: 350,
    originalPrice: 500,
    isBestSeller: false,
    category: "Non Fiction",
    rating: 2,
  },
  {
    _id: uuid(),
    img: "https://res.cloudinary.com/dgiibcwd7/image/upload/v1689069041/ecommerce-images/book_the-monk_robinsharma_kshgwj.jpg",
    name: "Monk Who Sold His Ferrari",
    author: "Robin Sharma",
    price: 119,
    originalPrice: 249,
    isBestSeller: false,
    category: "Non Fiction",
    rating: 3,
  },
  {
    _id: uuid(),
    img: "https://res.cloudinary.com/dgiibcwd7/image/upload/v1689069091/ecommerce-images/41xM13E3JwL_fkrkdz.jpg",
    name: "One Indian Girl",
    author: "Chetan Bhagat",
    price: 157,
    originalPrice: 195,
    isBestSeller: false,
    category: "Fiction",
    rating: 3,
  },
  {
    _id: uuid(),
    img: "https://res.cloudinary.com/dgiibcwd7/image/upload/v1689069103/ecommerce-images/61xPDmYV7SL._AC_UF1000_1000_QL80__kdg7tg.jpg",
    name: "Learning How To Fly",
    author: "A.P.J Abdul Kalam",
    price: 163,
    originalPrice: 205,
    isBestSeller: false,
    category: "Fiction",
    rating: 2.5,
  },
  {
    _id: uuid(),
    img: "https://res.cloudinary.com/dgiibcwd7/image/upload/v1689069141/ecommerce-images/61wipuAV0uL._AC_UF1000_1000_QL80__ts69ql.jpg",
    name: "400 Days",
    author: "Chetan Bhagat",
    price: 699,
    originalPrice: 999,
    isBestSeller: false,
    category: "Horror",
    rating: 4,
  },
  {
    _id: uuid(),
    img: "https://res.cloudinary.com/dgiibcwd7/image/upload/v1689069159/ecommerce-images/710jnzKlDTL._AC_UF894_1000_QL80__b2sexv.jpg",
    name: "Attitude Is Everything",
    author: "Keller Jeff",
    price: 399,
    originalPrice: 699,
    isBestSeller: false,
    category: "Horror",
    rating: 3.5,
  },
  {
    _id: uuid(),
    img: "https://res.cloudinary.com/dgiibcwd7/image/upload/v1689069218/ecommerce-images/71OLtGMB0PL._AC_UF1000_1000_QL80__xfmvex.jpg",
    name: "Man's Search For Meaning",
    author: "Franky Viktor",
    price: 243,
    originalPrice: 349,
    isBestSeller: false,
    category: "Non Fiction",
    rating: 1,
  },

  {
    _id: uuid(),
    img: "https://res.cloudinary.com/dgiibcwd7/image/upload/v1689067228/ecommerce-images/9781526604743_qcj5i0.jpg",
    name: "Kite Runner",
    author: "Khaled Hosseini",
    price: 109,
    originalPrice: 399,
    isBestSeller: true,
    category: "Horror",
    rating: 4.3,
  },
  {
    _id: uuid(),
    img: "https://res.cloudinary.com/dgiibcwd7/image/upload/v1689067332/ecommerce-images/71OcyQo_XPL._AC_UF1000_1000_QL80__qwqncy.jpg",
    name: "The Five-Star Weekend",
    author: "Elin Hilderbrand",
    price: 285,
    originalPrice: 1200,
    isBestSeller: false,
    category: "Horror",
    rating: 4,
  },

  {
    _id: uuid(),
    img: "https://res.cloudinary.com/dgiibcwd7/image/upload/v1689067569/ecommerce-images/61897971_fuzbs7.jpg",
    name: "The Quiet Tenant",
    author: "Clémence Michallon",
    price: 590,
    originalPrice: 500,
    isBestSeller: false,
    category: "Fiction",
    rating: 2,
  },
  {
    _id: uuid(),
    img: "https://res.cloudinary.com/dgiibcwd7/image/upload/v1689067778/ecommerce-images/81KXPEJhDML._AC_UF1000_1000_QL80__mathso.jpg",
    name: "Maeve Fly",
    author: "C.J. Leede",
    price: 567,
    originalPrice: 790,
    isBestSeller: true,
    category: "Horror",
    rating: 4.8,
  },

  {
    _id: uuid(),
    img: "https://res.cloudinary.com/dgiibcwd7/image/upload/v1689067901/ecommerce-images/41N4b-ptMnL._AC_UF1000_1000_QL80__vgafo9.jpg",
    name: "Fat Witch Summer",
    author: "Lizzy Ives",
    price: 489,
    originalPrice: 1500,
    isBestSeller: false,
    category: "Non Fiction",
    rating: 4,
  },
  {
    _id: uuid(),
    img: "https://res.cloudinary.com/dgiibcwd7/image/upload/v1689068007/ecommerce-images/9780593471920_ncpykb.jpg",
    name: "Dead Eleven",
    author: "Jimmy Juliano",
    price: 235,
    originalPrice: 500,
    isBestSeller: false,
    category: "Non Fiction",
    rating: 2,
  },
  {
    _id: uuid(),
    img: "https://res.cloudinary.com/dgiibcwd7/image/upload/v1689068079/ecommerce-images/91h2180IvoL._AC_UF1000_1000_QL80__taknrm.jpg",
    name: "Where Echoes Die",
    author: "Courtney Gould",
    price: 789,
    originalPrice: 249,
    isBestSeller: false,
    category: "Non Fiction",
    rating: 3,
  },
  {
    _id: uuid(),
    img: "https://res.cloudinary.com/dgiibcwd7/image/upload/v1689068152/ecommerce-images/81TaF2bL9IL._AC_UF1000_1000_QL80__ry3zrn.jpg",
    name: "The Beach at Summerly",
    author: "Beatriz Williams",
    price: 900,
    originalPrice: 195,
    isBestSeller: false,
    category: "Fiction",
    rating: 3,
  },
  {
    _id: uuid(),
    img: "https://res.cloudinary.com/dgiibcwd7/image/upload/v1689068259/ecommerce-images/63222106_s53pyk.jpg",
    name: "The Spare Room",
    author: "Andrea Bartz",
    price: 876,
    originalPrice: 205,
    isBestSeller: false,
    category: "Fiction",
    rating: 2.5,
  },
  {
    _id: uuid(),
    img: "https://res.cloudinary.com/dgiibcwd7/image/upload/v1689068725/ecommerce-images/81fN7vlmT5L._AC_UF1000_1000_QL80__iv8rb4.jpg",
    name: "Save What's Left",
    author: "Elizabeth Castellano",
    price: 1000,
    originalPrice: 999,
    isBestSeller: false,
    category: "Horror",
    rating: 4,
  },
  {
    _id: uuid(),
    img: "https://res.cloudinary.com/dgiibcwd7/image/upload/v1689068532/ecommerce-images/81_tLsaPhEL._AC_UF1000_1000_QL80__z7jnyu.jpg",
    name: "House Woman",
    author: "Adorah Nworah",
    price: 698,
    originalPrice: 699,
    isBestSeller: false,
    category: "Horror",
    rating: 3.5,
  },
  {
    _id: uuid(),
    img: "https://res.cloudinary.com/dgiibcwd7/image/upload/v1689068625/ecommerce-images/62562854_snctlb.jpg",
    name: "Will They or Won't They",
    author: "Ava Wilder",
    price: 40,
    originalPrice: 349,
    isBestSeller: false,
    category: "Non Fiction",
    rating: 1,
  },
];